-- V20260528_005: Create order and order_item tables

CREATE TABLE t_order (
    id                      BIGINT          NOT NULL COMMENT '订单 ID',
    order_no                VARCHAR(64)     NOT NULL COMMENT '订单编号，唯一',
    user_id                 BIGINT          NOT NULL COMMENT '下单用户 ID',
    total_price             DECIMAL(12, 2)  NOT NULL COMMENT '订单总价',
    total_weight_kg         DECIMAL(10, 3)  NOT NULL COMMENT '总重量(kg)',
    total_volume_m3         DECIMAL(10, 4)  NOT NULL COMMENT '总体积(m³)',
    trade_mode              VARCHAR(32)     NOT NULL COMMENT '交易模式: AUTO_TRADE, MATCHING_ORDER',
    order_status            VARCHAR(32)     NOT NULL DEFAULT 'PENDING_CONFIRM' COMMENT '订单状态',
    warehouse_status        VARCHAR(32)     NULL COMMENT '仓库状态',
    delivery_status         VARCHAR(32)     NULL COMMENT '配送状态',
    customs_sync_status     VARCHAR(32)     NULL COMMENT '海关同步状态',
    consignee_name          VARCHAR(128)    NOT NULL COMMENT '收货人',
    cabin_no                VARCHAR(64)     NOT NULL COMMENT 'Cabin No.',
    contact_info            VARCHAR(128)    NULL COMMENT '联系方式',
    expected_delivery_time  DATETIME        NULL COMMENT '期望送达时间',
    remark                  VARCHAR(512)    NULL COMMENT '备注',
    ship_no                 VARCHAR(64)     NOT NULL COMMENT '船号',
    ship_name               VARCHAR(128)    NULL COMMENT '船名',
    ship_nationality        VARCHAR(64)     NOT NULL COMMENT '船籍',
    imo                     VARCHAR(32)     NULL COMMENT 'IMO 编码',
    mmsi                    VARCHAR(32)     NULL COMMENT 'MMSI 编码',
    berth_or_anchorage      VARCHAR(128)    NULL COMMENT '泊位或锚地',
    target_gps              VARCHAR(128)    NULL COMMENT '目标 GPS',
    shipping_agent_id       BIGINT          NOT NULL COMMENT '船舶代理人 ID',
    shipping_agent_name     VARCHAR(128)    NOT NULL COMMENT '船舶代理人名称',
    completed_at            DATETIME        NULL COMMENT '完成时间',
    created_at              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by              VARCHAR(64)     NULL COMMENT '创建人',
    updated_by              VARCHAR(64)     NULL COMMENT '更新人',
    deleted                 TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0-未删除, 1-已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_order_no (order_no),
    KEY idx_order_user_id (user_id),
    KEY idx_order_status (order_status),
    KEY idx_order_ship_no (ship_no),
    KEY idx_order_shipping_agent_id (shipping_agent_id),
    KEY idx_order_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';

CREATE TABLE t_order_item (
    id                  BIGINT          NOT NULL COMMENT '明细 ID',
    order_id            BIGINT          NOT NULL COMMENT '订单 ID',
    order_no            VARCHAR(64)     NOT NULL COMMENT '订单编号',
    product_id          BIGINT          NOT NULL COMMENT '商品 ID',
    sku_code            VARCHAR(64)     NOT NULL COMMENT 'SKU 编码',
    product_name_zh     VARCHAR(128)    NOT NULL COMMENT '下单时中文名称快照',
    product_name_en     VARCHAR(128)    NOT NULL COMMENT '下单时英文名称快照',
    unit_price          DECIMAL(12, 2)  NOT NULL COMMENT '下单时单价',
    quantity            INT             NOT NULL COMMENT '数量',
    unit_weight_kg      DECIMAL(10, 3)  NOT NULL COMMENT '单位重量(kg)',
    unit_volume_m3      DECIMAL(10, 4)  NOT NULL COMMENT '单位体积(m³)',
    line_amount         DECIMAL(12, 2)  NOT NULL COMMENT '行金额',
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by          VARCHAR(64)     NULL COMMENT '创建人',
    updated_by          VARCHAR(64)     NULL COMMENT '更新人',
    deleted             TINYINT         NOT NULL DEFAULT 0 COMMENT '逻辑删除: 0-未删除, 1-已删除',
    PRIMARY KEY (id),
    KEY idx_order_item_order_id (order_id),
    KEY idx_order_item_sku_code (sku_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单明细表';
